services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit 1
      interval: 5s
      timeout: 15s
      retries: 60

  postgres:
    image: postgres
    volumes:
      - ./database/01-createtables.sql:/docker-entrypoint-initdb.d/01-createtables.sql
      - ./database/02-storedprocedures.sql:/docker-entrypoint-initdb.d/02-storedprocedures.sql
    environment:
      POSTGRES_PASSWORD: "postgrespassword"
    ports:
      - "5432:5432"
  
  producer:
    build: ./src/kafka_producer
    depends_on:
      kafka:
          condition: service_healthy
      postgres:
          condition: service_started
  
  consumer:
    build: ./src/kafka_consumer
    depends_on:
      kafka:
          condition: service_healthy
      postgres:
          condition: service_started